M48
; DRILL file KiCad 10.0.6 date 2026-09-13T03:07:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T03:07:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.400
%
G90
G05
T1
X44.04Y-42.12
T2
X50.4Y-75.05
X50.4Y-96.95
M30
