# gowinlink_files.tcl - RTL of the HL2 side of the Gowin link (gateware/rtl/gowinlink)
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_uart_rx.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_uart_tx.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_crc8.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_prbs23.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_scrambler.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_ddr_out.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_ddr_in.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_tx_lanes.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_cmd_rx.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_cmd_mux.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_status_tx.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_rxpll.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_rev_train.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_fs_cmd.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gowinlink_hl2.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gl_cdc.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gl_rx_datapath.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gl_fastserial_tx.v
set_global_assignment -name VERILOG_FILE ../../rtl/gowinlink/gl_fastserial_rx.v
