#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright 2026 Franz Schöning, https://www.schoning.com
# Convert the HL2 NEORV32 configuration (neorv32_hl2.vhd + core/*.vhd, VHDL-2008) into one plain
# Verilog module, neorv32_hl2.v, for the iverilog simulations (gateware/sim/cpu). Same flow as
# NEORV32's rtl/verilog/Makefile (the former neorv32-verilog project): GHDL analysis + "ghdl synth
# --out=verilog". Run once after changing neorv32_hl2.vhd or updating the core; the output is committed.
# Needs GHDL 6.0.0 (docs/rawfront/TOOLCHAIN.md); override with GHDL=/path/to/ghdl.
set -e
cd "$(dirname "$0")"
GHDL=${GHDL:-/c/tools/ghdl-6.0.0/bin/ghdl}
B=build
rm -rf $B
mkdir -p $B
SRCS=$(sed 's|\$NEORV32_HOME/rtl/core/|core/|' core/file_list_core.f)
$GHDL -i --std=08 --work=neorv32 --workdir=$B $SRCS neorv32_hl2.vhd
$GHDL -m --std=08 --work=neorv32 --workdir=$B neorv32_hl2
{
  echo "// SPDX-License-Identifier: GPL-2.0-or-later AND BSD-3-Clause"
  echo "// Copyright 2026 Franz Schöning, https://www.schoning.com"
  echo "//"
  echo "// Generated by gateware/rtl/neorv32/convert.sh from neorv32_hl2.vhd and NEORV32 $(cat VERSION)"
  echo "// with $($GHDL --version | head -1). Do not edit; re-run the script instead."
  echo "// NEORV32: BSD-3-Clause, see LICENSE.neorv32."
  $GHDL synth --std=08 --work=neorv32 --workdir=$B --out=verilog neorv32_hl2
} > neorv32_hl2.v
rm -rf $B
echo "neorv32_hl2.v: $(wc -l < neorv32_hl2.v) lines"
