#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Franz Schöning, https://www.schoning.com
"""Build the NEORV32 rv32imc boot ROM, the demo application, the message-layer firmware and the radio health
console example for the raw front-end image hl2b5up_raw (standard library only).

Needs the xPack GNU RISC-V Embedded GCC (see docs/rawfront/TOOLCHAIN.md).
  python firmware/hl2neo/build.py                     build everything
  python firmware/hl2neo/build.py --callsign N0CALL   callsign the health console example sends in Morse
  python firmware/hl2neo/build.py --size              also print symbol sizes

Outputs:
  firmware/hl2neo/build/bootrom.elf, demo.elf, demo.bin, msg.elf, msg.bin, health.elf, health.bin
  gateware/variants/hl2b5up_raw/bootrom.mif   ROM contents for Quartus (32-bit words)
  gateware/sim/cpu/bootrom_neo.hex            the same for simulation ($readmemh)
  firmware/hl2neo/build/rom_syms.h            boot ROM receive-ring variable addresses (for msg)
  gateware/sim/front/msg_ram.hex              msg.bin as 32-bit RAM words from 0x800 (tb_msg)
"""

import argparse
import os
import shutil
import struct
import subprocess
import sys

ROM_VERSION = 0x00020000
ROM_WORDS = 1024            # 4 kB, must match CPU_ROM_WORDS in gateware/variants/hl2b5up_raw/hermeslite.v

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
BUILD = os.path.join(HERE, "build")
PREFIX = os.environ.get("RISCV_PREFIX", r"C:\tools\xpack-riscv-none-elf-gcc-15.2.0-1\bin\riscv-none-elf-")

CFLAGS = ["-march=rv32imc_zicsr", "-mabi=ilp32", "-Os", "-g", "-Wall", "-Wextra", "-ffreestanding", "-nostdlib",
          "-ffunction-sections", "-fdata-sections", "-msmall-data-limit=0", "-fno-delete-null-pointer-checks",
          "-I" + os.path.join(HERE, "common")]


def tool(name):
    exe = PREFIX + name
    if shutil.which(exe) is None and not os.path.exists(exe + ".exe"):
        sys.exit("RISC-V toolchain not found (%s); set RISCV_PREFIX" % exe)
    return exe


def run(cmd):
    r = subprocess.run(cmd)
    if r.returncode:
        sys.exit("failed: " + " ".join(cmd))


def elf(out, srcs, ld, extra):
    run([tool("gcc")] + CFLAGS + extra + ["-T", ld, "-Wl,--gc-sections", "-Wl,--no-warn-rwx-segments", "-o", out] + srcs + ["-lgcc"])


def objcopy_bin(elf_path, bin_path):
    run([tool("objcopy"), "-O", "binary", elf_path, bin_path])


def write_rom(bin_path):
    data = open(bin_path, "rb").read()
    if len(data) > ROM_WORDS * 4:
        sys.exit("boot ROM is %d bytes, larger than the %d-byte ROM" % (len(data), ROM_WORDS * 4))
    data += b"\x00" * (ROM_WORDS * 4 - len(data))
    words = struct.unpack("<%dI" % ROM_WORDS, data)
    mifs = [os.path.join(REPO, "gateware", "variants", v, "bootrom.mif") for v in ("hl2b5up_raw",)]
    hexf = os.path.join(REPO, "gateware", "sim", "cpu", "bootrom_neo.hex")
    os.makedirs(os.path.dirname(hexf), exist_ok=True)
    for mif in mifs:
        with open(mif, "w", newline="\n") as f:
            f.write("-- NEORV32 boot ROM %08x, generated by firmware/hl2neo/build.py\n" % ROM_VERSION)
            f.write("WIDTH=32;\nDEPTH=%d;\nADDRESS_RADIX=HEX;\nDATA_RADIX=HEX;\nCONTENT BEGIN\n" % ROM_WORDS)
            for i, w in enumerate(words):
                f.write("  %03x : %08x;\n" % (i, w))
            f.write("END;\n")
    with open(hexf, "w", newline="\n") as f:
        for w in words:
            f.write("%08x\n" % w)
    return len(open(bin_path, "rb").read())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", action="store_true")
    ap.add_argument("--callsign", default="N0CALL", help="callsign the health console sends in Morse on LED D5")
    args = ap.parse_args()
    os.makedirs(BUILD, exist_ok=True)

    rom_elf = os.path.join(BUILD, "bootrom.elf")
    rom_bin = os.path.join(BUILD, "bootrom.bin")
    elf(rom_elf, [os.path.join(HERE, "bootrom", "start.S"), os.path.join(HERE, "bootrom", "rom.c")],
        os.path.join(HERE, "bootrom", "link.ld"), ["-msave-restore", "-fno-jump-tables", "-fno-tree-loop-distribute-patterns",
                                               "-DROM_VERSION=0x%08x" % ROM_VERSION])
    objcopy_bin(rom_elf, rom_bin)
    n = write_rom(rom_bin)
    print("boot ROM: %d of %d bytes (%d free)" % (n, ROM_WORDS * 4, ROM_WORDS * 4 - n))

    demo_elf = os.path.join(BUILD, "demo.elf")
    demo_bin = os.path.join(BUILD, "demo.bin")
    elf(demo_elf, [os.path.join(HERE, "demo", "crt0.S"), os.path.join(HERE, "demo", "main.c")],
        os.path.join(HERE, "demo", "link.ld"), [])
    objcopy_bin(demo_elf, demo_bin)
    print("demo: %d bytes" % os.path.getsize(demo_bin))

    # raw front-end message firmware: needs the boot ROM's receive-ring variable addresses
    syms = {}
    for line in subprocess.run([tool("nm"), rom_elf], capture_output=True, text=True).stdout.splitlines():
        parts = line.split()
        if len(parts) == 3:
            syms[parts[2]] = int(parts[0], 16)
    with open(os.path.join(BUILD, "rom_syms.h"), "w", newline="\n") as f:
        f.write("/* generated by build.py from bootrom.elf (ROM %08x): boot ROM receive-ring variables */\n" % ROM_VERSION)
        f.write("#define ROM_RX_RD   (*(uint16_t *)0x%08xu)\n" % syms["rx_rd"])
        f.write("#define ROM_RX_LEFT (*(uint16_t *)0x%08xu)\n" % syms["rx_left"])
        f.write("/* console state, for applications that handle console attach datagrams themselves (health) */\n")
        f.write("#define ROM_CON_ATTACHED (*(uint8_t *)0x%08xu)\n" % syms["con_attached"])
        f.write("#define ROM_GDB_ATTACHED (*(uint8_t *)0x%08xu)\n" % syms["gdb_attached"])
        f.write("#define ROM_GDB_RUNNING  (*(uint8_t *)0x%08xu)\n" % syms["gdb_running"])
        f.write("#define ROM_RING_SENT    (*(uint32_t *)0x%08xu)\n" % syms["ring_sent"])
    msg_elf = os.path.join(BUILD, "msg.elf")
    msg_bin = os.path.join(BUILD, "msg.bin")
    elf(msg_elf, [os.path.join(HERE, "demo", "crt0.S"), os.path.join(HERE, "msg", "main.c"), os.path.join(HERE, "msg", "msg.c")],
        os.path.join(HERE, "demo", "link.ld"), ["-I" + BUILD, "-Wno-array-bounds"])
    objcopy_bin(msg_elf, msg_bin)
    data = open(msg_bin, "rb").read()
    print("msg: %d bytes" % len(data))
    data += b"\x00" * (-len(data) % 4)
    with open(os.path.join(REPO, "gateware", "sim", "front", "msg_ram.hex"), "w", newline="\n") as f:
        for i in range(0, len(data), 4):
            f.write("%08x\n" % struct.unpack_from("<I", data, i)[0])

    # radio health console example (health/main.c): reads the receive ring itself, as msg does
    call = args.callsign.upper()
    if not call or len(call) > 15 or any(c not in "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/ " for c in call):
        sys.exit("--callsign: up to 15 letters, digits, '/' or spaces")
    health_elf = os.path.join(BUILD, "health.elf")
    health_bin = os.path.join(BUILD, "health.bin")
    elf(health_elf, [os.path.join(HERE, "demo", "crt0.S"), os.path.join(HERE, "health", "main.c")],
        os.path.join(HERE, "demo", "link.ld"), ["-I" + BUILD, "-Wno-array-bounds", '-DCALLSIGN="%s"' % call])
    objcopy_bin(health_elf, health_bin)
    print("health: %d bytes, callsign %s" % (os.path.getsize(health_bin), call))

    if args.size:
        for e in (rom_elf, demo_elf, msg_elf, health_elf):
            run([tool("nm"), "--size-sort", "-S", "-t", "d", e])


if __name__ == "__main__":
    main()
